<table border="0" cellpadding="1" cellspacing="1" style="width:800px">
	<tbody>
		<tr>
			<td>
			<table align="left" border="1" cellpadding="1" cellspacing="1" style="width:800px">
				<tbody>
					<tr>
						<td style="width:40px"><? php echo . $row['id'].;</td>
						<td style="width:650px">Description</td>
						<td style="width:110px">Status</td>
					</tr>
				</tbody>
			</table>
			</td>
		</tr>
		<tr>
			<td>
			<table align="left" border="1" cellpadding="1" cellspacing="1" style="width:800px">
				<tbody>
					<tr>
						<td style="width:100px">Cost:</td>
						<td style="width:300px">&nbsp;</td>
						<td style="width:100px">Date Aquired:</td>
						<td style="width:300px">&nbsp;</td>
					</tr>
					<tr>
						<td style="width:66px">Source:</td>
						<td style="width:326px">&nbsp;</td>
						<td style="width:96px">Size:</td>
						<td style="width:272px">&nbsp;</td>
					</tr>
				</tbody>
			</table>
			</td>
		</tr>
	</tbody>
</table>
